### PR TITLE
Fix issue when creating dataTypes

### LINKED ISSUE #318: Adding new Data Type updates existing Data Type
**Describe the bug**
When editing an Element in a Class, clicking on 'Add a new Data Type' updates the Element's current Data Type to the selected values, rather than creating a new Data Type.

**To Reproduce**

Below steps are for example in development version.

1. Go to Complex Test Data model and add two integer elements as below:
Screen Shot 2021-09-16 at 15 42 45

2. Click Add a new Data Type and select a Reference to the content class. N.B. some red error text appears which is probably not necessary:
Screen Shot 2021-09-16 at 15 49 49
Screen Shot 2021-09-16 at 15 45 49

3. Then the integer data type is updated to be a content class reference:
Screen Shot 2021-09-16 at 15 45 26
Screen Shot 2021-09-16 at 16 13 43

**Expected behavior**
New Data Type should be added and only the selected Element being edited should have its Type changed.

**Versions**
Reproduced on Mauro version 6.6.0 (in mdm-docker) and version 6.7.0-SNAPSHOT (development version).

### PR DESCRIPTION
**Pull request by CristianGimenez**
This PR will be marked as "Draft" because it depends on a [PR for mdm-resources](https://github.com/MauroDataMapper/mdm-resources/pull/104).

The main cause of the issue was that `new-data-type-inline.component` was using an anonymous type with the wrong variable names, and `default-profile-editor-modal.component` was using those variable names without treating them. All this is allowed because the `DataType`definition allows `[key : string]: value` as a variable.

There is a number of changes in this PR:
- Removing unused validations and some small fixes that I spotted while working in the different components.
- Removing anonymous types to use `DataType`.
- Adding some comments on the code to describe better what needs to happen or why we do certain transformations.
- When creating a new `DataType` the label for the new `dataType `is mandatory, so we should show the fields from the start.

Both creating a new `dataType` while editing an existing `dataElement `and when creating a brand new `dataElement `should work fine now.

closes #318

### CODE REVIEW

File: src/app/dataElement/data-element/data-element.component.ts [hunk 1]
```diff
@@ -221,7 +215,20 @@ export class DataElementComponent
         resource.minMultiplicity = item.minMultiplicity as number;
         resource.maxMultiplicity = item.maxMultiplicity;
       } else if (item.controlType === ProfileControlTypes.dataType) {
-        resource.dataType = item.value as DataTypeReference;
+        const castedValue = item.value as DataType;
```
Comment (abwilson23) [inline src/app/dataElement/data-element/data-element.component.ts]: Not a necessary change but given we've identified that `item.controlType` is `datatype` a more descriptive name than `castedValue` might be `dataTypeValue`.

File: src/app/data-type/data-type.component.ts [hunk 2]
```diff
@@ -129,8 +132,6 @@ export class DataTypeComponent extends BaseComponent
 
         this.dataType.classifiers = this.dataType.classifiers || [];
         this.loadingData = false;
-        this.showExtraTabs =
-          !this.sharedService.isLoggedIn() || !this.dataType.editable;
```
Comment (abwilson23) [inline src/app/data-type/data-type.component.ts:133]: Just a note that you can remove the injected SharedService from the the constructor as this was the only use of it.

**Review by abwilson23 — DISMISSED** [review]
Couple of small comments, but overall code changes appear sensible and concise. The functional testing went well, changing data types and adding new ones has the described and desired behaviour. 

It appears there are some jenkins tests to sort out still before it can be merged.

File: src/app/dataElement/data-element/data-element.component.ts (hunk 1 above)
Comment (CristianGimenez) [reply src/app/dataElement/data-element/data-element.component.ts]: Makes sense, changing.

File: src/app/data-type/data-type.component.ts (hunk 2 above)
Comment (CristianGimenez) [reply src/app/data-type/data-type.component.ts:133]: Done

**Comment by CristianGimenez** [comment]
@abwilson23 I've addressed your comments in the latest commit. Could you resolve the comments if you are happy? Whatever Jenkins was unhappy about seems to be ok now.

**Review by abwilson23 — APPROVED** [review]
Approved ✅

**Comment by jamesrwelch** [comment]
@abwilson23 @CristianGimenez I'm happy to merge this now, if you're both happy?

**Comment by CristianGimenez** [comment]
> @abwilson23 @CristianGimenez I'm happy to merge this now, if you're both happy?

Yes please, thanks!

**Comment by jamesrwelch** [comment]
Fantastic work both of you 👍
